### ISSUE TITLE
[Atividade]Criar o Card Entrega de  Material

### ISSUE THREAD

**Issue by pvcs15** [amadeusproject/uxdesign-html#27]
- [ ] Integrar Card à uma screen

**Comment by fbormann** [comment]
O card está no design correto.

[PT-BR] 
Lendo seus commits, existem os seguintes erros:

- Tag <script> aberta e que não é necessária "$( function() {
    $( "#datepicker" ).datepicker();
    $("#datepicker2").datepicker();
  } );", crie um arquivo .js para utlizá-la.

- Não utilizou uma div "container" nem "row" na page.
- utilizou somente "col-md", isto não é o suficiente para tornar o site agradavelmente responsivo (procure por "col-sm"/"col-xs").
- Os arquivos de .css do material e do bootstrap não estão carregando pois o caminho está errado.
- Um arquivo .js do jquery tá sendo carregado via "url", o baixe e o utilize localmente, é melhor.

[EN-US]

-  <script> Tag is open but is not on the right place  "$( function() {
    $( "#datepicker" ).datepicker();
    $("#datepicker2").datepicker();
  } );", create a .js file to use it.

- Neither of "container" and "row" classes were used.
- Used only "col-md" classes, that is not enough to make the card responsive.(look for "col-sm" and "col-xs").

- .css files from material and bootstrap aren't being loaded because the path is wrong.
- A .js file from jquery is being loaded through url, download it and use it locally.

**Comment by pvcs15** [comment]
Como assim tag? Esse Card vai ser incorporado ao template

Em 11 de set de 2016 12:40 PM, "Felipe Bormann" <notifications@github.com>
escreveu:

**Comment by fbormann** [comment]
@pvcs15  <html> é uma html tag, <script> é uma script Tag.

**Comment by pvcs15** [comment]
a function é algo pequeno. não existe necessidade de criar um arquivo .js somente pra uma function pra uma tela em especifico.

Não usei o ROW, pois no site ja vem assim, creio que o form-group ja serve. e eu usei o container-fluid e nao container. 

sobre o .css é questao que no meu diretorio nao precisa de 3 "../"
e eu uso via url pois acho mais leve de mexer.

**Comment by santojon** [comment]
@ pvcs15, o javascript na verdade fica melhor em um arquivo a parte. Outras modificações posteriores podem vir a serem feitas no arquivo .js. Isso ajuda a separar a informação da página do comportamento.

**Comment by pvcs15** [comment]
como eu disse, apesar de não ser uma boa pratica, uma function com 5 linhas e de exclusividade pra um card do projeto, não vejo o porque de criar um arquivo. igualmente pro .css

**Comment by fbormann** [comment]
Não tem commit relacionado à esta issue, não sei o que corrigir.

**Comment by pvcs15** [comment]
claro que tem, mas ta como material_delivery_....

depois tu coloca ela em fechada

**Comment by pvcs15** [comment]
Material_delivery_teacher.html. eu commitei faz dois dias.

Em 19 de set de 2016 1:14 PM, "Felipe Bormann" <notifications@github.com>
escreveu:

**Comment by thiagosoara** [comment]
@fbormann preciso que tu faça o review dessa atividade, ela já foi completada.

Fico no aguardo.

**Comment by juliotoscano** [comment]
@pvcs15 Esse Card precisa estar integrado à uma screen.
